### ISSUE TITLE
Pass through device

### ISSUE THREAD

**Issue by sjdellis** [Jip-Hop/jailmaker#100]
Any way to pass through device /dev/kvm ?

Would be great to get this running https://github.com/dockur/windows in jailmaker, or is there another way?

**Comment by Lockszmith-GH** [comment]
That's something that should be researched with Systemd-nspawn,  
Looking at [https://wiki.archlinux.org/title/Systemd-nspawn#3D_graphics_acceleration](https://wiki.archlinux.org/title/Systemd-nspawn#3D_graphics_acceleration) for example, the phrase "bind mount `/dev/dri`" shows up, so I guess device binding is possible to a degree.

Remember, all that jailmaker does, is help manage the initialization of the system so that systemd-nspawn can be used, everything else is about workgin with systemd-nspawn on a debian host.

**Comment by sjdellis** [comment]
> That's something that should be researched with Systemd-nspawn, Looking at https://wiki.archlinux.org/title/Systemd-nspawn#3D_graphics_acceleration for example, the phrase "bind mount `/dev/dri`" shows up, so I guess device binding is possible to a degree.
> 
> Remember, all that jailmaker does, is help manage the initialization of the system so that systemd-nspawn can be used, everything else is about workgin with systemd-nspawn on a debian host.

Amazing. Thank you @Lockszmith-GH 

I added --bind=/dev/kvm to my config and all is good. 

This is an awesome project and should be part of TrueNAS.

**Comment by Jip-Hop** [comment]
Glad you got it working. However mounting /dev/kvm may have side effects. I ran into this when experimenting with LXD: https://github.com/Jip-Hop/jailmaker/tree/main/templates/lxd#scale-virtual-machines

I think it was caused by LXD changing ownership and/or permissions on /dev/kvm.

So if VMs in the SCALE GUI suddenly stop working for you then you have an idea where to look for the solution.

And thanks @Lockszmith-GH for helping out :)

**Comment by sjdellis** [comment]
> Glad you got it working. However mounting /dev/kvm may have side effects. I ran into this when experimenting with LXD: https://github.com/Jip-Hop/jailmaker/tree/main/templates/lxd#scale-virtual-machines
> 
> I think it was caused by LXD changing ownership and/or permissions on /dev/kvm.
> 
> So if VMs in the SCALE GUI suddenly stop working for you then you have an idea where to look for the solution.
> 
> And thanks @Lockszmith-GH for helping out :)

So far my VM's are not affected. Will update if things change 👍
