### ISSUE TITLE
AMD GPU passthrough support

### ISSUE THREAD

**Issue by gardenali** [Jip-Hop/jailmaker#109]
It's great to have intel and nvidia support, but I'm missing the AMD option.

Thank you!

**Comment by lks-hrsch** [comment]
I am currently also at the point that I need amd gpu support to move my last service to jailmaker. Can someone explain what is needed to enable gpu support or what you have done for intel and nvidia? I am open to implementing and evaluating the feature on my system.

**Comment by easyfab** [comment]
Does it work if you manually add --bind=/dev/dri  ?

e.g :  jlmkr create myjail --bind=/dev/dri

**Comment by jeefberkey** [comment]
The intel gpu setting does just that

**Comment by Jip-Hop** [comment]
Jailmaker has intel and nvidia GPU support because these drivers are provided by the TrueNAS SCALE host OS. I think adding support for a dedicated AMD GPU in jailmaker is not trivial, if possible at all without modifying the host OS. Since I have no dedicated GPU in my TrueNAS server I can't investigate this. Feel free to investigate though. @lks-hrsch you could have a look at the python code of `jlmkr.py` to see what the intel and nvidia GPU passthrough options do.

**Comment by easyfab** [comment]
Isn't AMD support in Truenas Host OS ?

lspci -k | grep amdgpu
Kernel driver in use: amdgpu
Kernel modules: amdgpu


For info, I tried with 5700G APU, adding --bind=/dev/dri seems  to give  me access to the igpu in jailmaker.
Don't know if it work with dgpu.

**Comment by Jip-Hop** [comment]
Yes I think there's a difference between AMD iGPU and dGPU but I'd be happy to be proven wrong.

**Comment by Jip-Hop** [comment]
I've labeled this issue as _invalid_ and _help wanted_. I think iGPU is already supported (Intel or AMD). You'd have to set `gpu_passthrough_intel=1` in your config file for that. I realize now this naming is confusing in this case...

Regarding AMD dedicated GPUs, as far as I know those aren't supported on the SCALE host system and therefore jailmaker can't support them either.

Since I don't have an AMD GPU I could use help to confirm this issue is indeed invalid. Either way, I won't be working on a solution for this issue and I recommend to either switch to an nvidia GPU or implement a solution (if possible) and provide a pull request.

**Comment by lks-hrsch** [comment]
I apologize for not getting back to you sooner, but I can prove that for AMD iGPU it's already working, a dGPU I also currently don't have for testing.

**Comment by maeehart** [comment]
Hey! I just want to add that that passing the AMD gpu does work, but one needs to also bind `/dev/kfd`. That is, the command like 
`./jlmkr.py create --distro=ubuntu --release=jammy ubuntu --bind=/dev/dri --bind=/dev/kfd`
works. After this, I just had a bit of problems with permissions on these files. However, now I can run llama3 in a jail using an AMD GPU.

**Comment by Jip-Hop** [comment]
@maeehart is that a dedicated AMD GPU you're using (which model)? If so then that's good news and we can close this ticket as completed.

**Comment by maeehart** [comment]
Yes, it is a 6900 xt, i.e., a dedicated AMD GPU.  We could still make a PR regarding the AMD support so that one could just ues the GPU by adding a `gpu_passthrough_amd` flag.

**Comment by Jip-Hop** [comment]
Ah yes that's a good idea. Could you provide the PR?

**Comment by maeehart** [comment]
I can do it during the weekend. I will need to see if I can do something about the permissions.

**Comment by dalgibbard** [comment]
Though you didn't specify what your permission issues are; is it fixed if you add:
```--property=DeviceAllow="/dev/kfd rw"```
?

I ask, since I do something similar for CoralTPU passthrough, which looks like:
```
--bind='/dev/ttyUSB0'
--property=DeviceAllow="/dev/ttyUSB0 rwm"
--property=DeviceAllow="char-drm rwm"
--property=DeviceAllow=/dev/bus/usb
```
Though I haven't spent enough time in the land of nspawn to really work out if all of these are necessary/correct lol

**Comment by jere-co** [comment]
Any updates on the AMD dGPU support?

**Comment by Jip-Hop** [comment]
> Hey! I just want to add that that passing the AMD gpu does work, but one needs to also bind `/dev/kfd`. That is, the command like

@maeehart are you sure it was the AMD GPU being used (and not the one in the CPU because you also added `--bind=/dev/dri`)? I assume the AMD GPU should be usable without `--bind=/dev/dri`, at least this is the case for an NVIDIA GPU. Which commands did you run in the jail to test the AMD GPU?

I have an AMD RX 580 GPU in a test TrueNAS server but couldn't yet get it working in an ubuntu jail. I tried debugging with `mpv --hwdec=auto video_filename` from [this arch resource](https://wiki.archlinux.org/title/Hardware_video_acceleration).

**Comment by maeehart** [comment]
Hey! I am sure that it is the AMD GPU. I have been now running ollama in the jail and confirming that the GPU is running with watching rocm-smi command for some time. However, I have not had the time to do it again so that I could add the proper scrip to this repo and I am sorry about that. I remember that I had to bind both /dev/dri and /dev/fkd and then modify their rights to allow writing to these files (chmod ...).

**Comment by Jip-Hop** [comment]
Instead of messing with permissions of `/dev/kfd` can't you run the process in your jail as under the same user/group which already owns `/dev/kfd`?

**Comment by maeehart** [comment]
I think that that is a much better idea.

**Comment by Jip-Hop** [comment]
Reportedly AMD GPU passthrough works:

```
 ./jlmkr.py create --distro=ubuntu --release=jammy ubuntu --bind=/dev/dri --bind=/dev/kfd
```

Adding a dedicated AMD GPU passthrough config option, with corresponding flag for the create command, seems like overkill when a single additional bind mount is enough (especially since AMD GPU passthrough reportedly relies on `/dev/dri` being mounted which `gpu_passthrough_intel=1` takes care of).

**Comment by tyvsmith** [comment]
Suggest documenting this more widely, like in primary readme, or revisiting the decision not to include a flag (even if it's simple). I started investigating jailmaker to handle my k3s -> Docker conversion for Truenas scale, and it wasn't clear if AMD gpu's were supported at all until finding this ticket and reading comments.

**Comment by Jip-Hop** [comment]
Updated the readme!

**Comment by krupinskika** [comment]
Can confirm hardware transcoding for AMD 5700G works.
