### ISSUE TITLE
Recreate/Update Symlink on re-install or unistall option?

### ISSUE THREAD

**Issue by Nostang3** [Jip-Hop/jailmaker#117]
I am running a new temp machine with scale 23.10 to try and figure out how to setup docker in jailmaker so I can install portainer and move my apps over on my main machine. Not important to the issue but maybe need to know info later. 

I originally created a dataset and ran jlmkr.py install with that dataset. I couldn't get docker to create a hello world so I decided to start fresh. But now when I try to run install on a new dataset it still links to the old dataset. I didn't see any commands to edit the symlink/alias and isn't prompted when trying to install again and fails with no such file or directory. Nor did I see a uninstall option to remove them. Can we get an uninstall option to remove the symlink/alias and/or everything it did to be able to start fresh? I'm sure there is a non-newb way to just delete the symlink/alias in the system but I'd feel better if there was an official built in way so I don't miss something as I don't know all of what is run. 

Title needs work.

**Comment by Jip-Hop** [comment]
You can remove the symlink manually. The symlink won't work on the next release of SCALE (24.4) anyway. It can't be created because of readonly rootfs. So this symlink aproach can be considered deprecated.

However I think the symlink should have been updated automatically when running the `jlmkr.py install` again:

https://github.com/Jip-Hop/jailmaker/blob/f046dd3d3202aa8f377ce0e447e4718959f0db3e/jlmkr.py#L1732-L1736

Did you look in `/root/.bashrc` and `/root/.zshrc`? Is the alias pointing to the old or new install location?
