### ISSUE TITLE
docker template install version is bad

### ISSUE THREAD

**Issue by davistw1** [Jip-Hop/jailmaker#158]
Template installs docker version 26.0.2 which breaks Virtual Machine networking.

**Comment by Jip-Hop** [comment]
I don't think this is true. The template installs the latest version. Besides that the template uses macvlan or bridge networking so the jail has its own network namespace. I have a hard time imagining how this breaks VM networking. And I need to use my imagination because the issue contains no details or logging. 😅

**Comment by davistw1** [comment]
I believe you are absolutely right. I tried a install and it blew up originally. I read on the forum where it said that the problem was installing the latest version and to back down to the previous. Hence my issue. That said I followed the video that stux posted and it worked like a champ with the latest version. Sorry. PS thanks...
